db:
  image: postgres
  environment:
    - POSTGRES_USER=yatu
  ports:
    - "5432:5432"

liquibase:
  build: db-schema/
  environment:
    - DB_USER=yatu
    - DB_SCHEMA_NAME=yatu
  links:
    - db

rabbitmq:
  image: rabbitmq:3-management
  environment:
    - RABBITMQ_ERLANG_COOKIE=secret_cookie
    - RABBITMQ_DEFAULT_PASS=123
  ports:
    - "8888:15672"
    - "5672:5672"

celeryworker:
  build: celery_worker/
  environment:
    - C_FORCE_ROOT=1
  links:
    - db
    - rabbitmq

api:
  build: api/
  links:
    - db
    - rabbitmq
    - celeryworker
  ports:
    - "8080:80"
