db:
  image: postgres
  environment:
    - POSTGRES_USER=yatu
  ports:
    - "5432:5432"

liquibase:
  build: apps/db-schema/
  environment:
    - DB_USER=yatu
    - DB_SCHEMA_NAME=yatu
  links:
    - db

rabbitmq:
  image: rabbitmq:3-management
  environment:
    - RABBITMQ_ERLANG_COOKIE=secret_cookie
    - RABBITMQ_DEFAULT_PASS=123
  ports:
    - "8888:15672"
    - "5672:5672"